#!/bin/sh

if [ -z "$PROJECT" ]
then
    PROJECT="$HOME/repos/sourcehut/wareification/lngrd"
fi

cd "$PROJECT"

standards='c89 c99 c11 c17'
stdout=/dev/null
stderr=`mktemp`

for standard in $standards
do
    make -s clean
    make -s CFLAGS='-std=c17 -pedantic -Wall -Werror -Wextra'

    if [ $? -ne 0 ]
    then
        exit 1
    fi

    abort()
    {
        make -s clean
        exit 1
    }

    trap abort INT QUIT ABRT

    make -s check clean 1> "$stdout" 2> "$stderr"

    if [ $? -ne 0 ]
    then
        cat "$stderr" 1>&2
        rm "$stderr"
        exit 1
    fi
done

cat "$stderr" 1>&2
rm "$stderr"
