#!/bin/sh

if [ -z "$PROJECT" ]
then
    PROJECT="$HOME/repos/sourcehut/wareification/lngrd"
fi

cd "$PROJECT"
make -s clean
make -s CC='g++' CFLAGS='-ansi -pedantic -Wall -Werror -Wextra -Wno-deprecated'

if [ $? -ne 0 ]
then
    exit 1
fi

abort()
{
    make -s clean
    exit 1
}

trap abort INT QUIT ABRT

make -s check clean
