#!/bin/sh

if [ ! -e check-cxx -o ! -e check-cpp -o ! -e check-sanitizers -o ! -e check-valgrind -o ! -e check-powerpc ]
then
    exit 1
fi

if [ -z "$NO_COLOR" ]
then
    printf '\033[1;4mCXX\033[0m\n' 1>&2
else
    printf 'CXX\n' 1>&2
fi
./check-cxx
printf '\n' 1>&2

if [ -z "$NO_COLOR" ]
then
    printf '\033[1;4mCPP\033[0m\n' 1>&2
else
    printf 'CPP\n' 1>&2
fi
./check-cpp
printf '\n' 1>&2

if [ -z "$NO_COLOR" ]
then
    printf '\033[1;4mSanitizers\033[0m\n' 1>&2
else
    printf 'Sanitizers\n' 1>&2
fi
./check-sanitizers
printf '\n' 1>&2

if [ -z "$NO_COLOR" ]
then
    printf '\033[1;4mValgrind\033[0m\n' 1>&2
else
    printf 'Valgrind\n' 1>&2
fi
./check-valgrind
printf '\n' 1>&2

if [ -z "$NO_COLOR" ]
then
    printf '\033[1;4mPowerPC\033[0m\n' 1>&2
else
    printf 'PowerPC\n' 1>&2
fi
./check-powerpc
printf '\n' 1>&2
