#!/bin/sh

if [ -z "$PROJECT" ]
then
    PROJECT="$HOME/repos/sourcehut/wareification/lngrd"
fi

if [ ! `command -v valgrind` ]
then
    if [ -z "$NO_COLOR" ]
    then
        printf '\033[7;31m FAIL \033[0m\n' 1>&2
        printf '\033[1mReason:\033[0m\n' 1>&2
    else
        printf '[FAIL]\n' 1>&2
        printf 'Reason:\n' 1>&2
    fi

    printf "valgrind not available\n" 1>&2

    exit 1
fi

cd "$PROJECT"
make -s clean
make -s CFLAGS='-ansi -pedantic -Wall -Werror -Wextra -g3'

if [ $? -ne 0 ]
then
    exit 1
fi

abort()
{
    rm valgrind-log.txt
    cd "$PROJECT"
    make -s clean
    exit 1
}

trap abort INT QUIT ABRT

cd test
valgrind --leak-check=full --error-exitcode=64 -q --log-file=valgrind-log.txt ../bin/lngrd check
status=$?

if [ -f valgrind.log.txt -a -s valgrind-log.txt ]
then
    if [ -z "$NO_COLOR" ]
    then
        printf '\033[7;33m LEAK \033[0m\n' 1>&2
        printf '\033[1mReason:\033[0m\n' 1>&2
        printf "memory test failed\n" 1>&2
        printf '\033[1mLog:\033[0m\n' 1>&2
    else
        printf '[FAIL]\n' 1>&2
        printf 'Reason:\n' 1>&2
        printf "memory test failed\n" 1>&2
        printf 'Log:\n' 1>&2
    fi

    cat valgrind-log.txt 1>&2
fi

rm valgrind-log.txt

cd "$PROJECT"
make -s clean
exit $status
